[config]
rpc = "https://rpc.kunalabs.io:443"

[packages]
KaiSingleAssetVault = { local = "../../../../../move/kai/sav/core" }
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet-v1.55.0", override = true }
MoveStdlib = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/move-stdlib", rev = "mainnet-v1.55.0", override = true }
CetusClmm = { local = "../../../../../move/_vendor/CetusClmm" }
CetusIntegrate = { local = "../../../../../move/_vendor/CetusIntegrate" }
IntegerMate = { local = "../../../../../move/_vendor/IntegerMate", override = true }
KaiLeverage = { local = "../../../../../move/kai/leverage/core" }
KaiLeverageUtil = { local = "../../../../../move/kai/leverage/util" }
Pyth = { local = "../../../../../move/_vendor/Pyth" }
Wormhole = { local = "../../../../../move/_vendor/Wormhole" }
bluefin_spot = { local = "../../../../../move/_vendor/bluefin_spot" }
